<?php
/**
 * Created by PhpStorm.
 * User: purwa
 * Date: 6/14/17
 * Time: 5:39 PM
 */

namespace app\models;


use yii\web\UploadedFile;

class FileUpload extends TranFileUpload
{
	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'nama' => 'Nama',
			'jenis' => 'Jenis',
			'deskripsi' => 'Deskripsi',
			'path' => 'Berkas',
			'id_jenis' => 'Id Jenis',
		];
	}
	
	public function rules()
	{
		$rules = parent::rules(); // TODO: Change the autogenerated stub
		return array_merge($rules,[]);
	}
	
	public function saveUpload()
	{
		
		$file = UploadedFile::getInstance($this, 'path');
		$this->nama = $file->name;
		$dir = \Yii::$app->params['uploadPath'].base64_encode($this->jenis.$this->id_jenis);
		
		if(!is_dir($dir))
			mkdir($dir);
		$filepath = $dir.'/'.base64_encode($this->nama).'.'.$file->getExtension();
		
		$this->path = $filepath;
		$this->deskripsi = $this->nama;
		if($file->saveAs($filepath))
			return $this->save();
	}
}